version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.9.3-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - run:
                name: environment file
                command: curl -H "Authorization:token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw" -O -L $ENVIRONMENT
            - run:
                name: environment prod file
                command: curl -H "Authorization:token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw" -O -L $ENVIRONMENT_PROD
            - run:
                name: delete old enviornment file
                command: rm -rf src/environments/environment.ts
            - run:
                name: delete old enviornment file
                command: rm -rf src/environments/environment.prod.ts
            - run:
                name: copy new files
                command: cp environment.ts src/environments/environment.ts
            - run:
                name: copy new files
                command: cp environment.prod.ts src/environments/environment.prod.ts
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: npm run lint
            - run:
                name: Testing
                command: npm run test-prod
            - run:
                name: Building
                command: npm run build-prod
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
                    - package.json
                    - firebase.json
                    - .firebaserc

    deploy:
        docker:
            - image: circleci/node:8.9.3-browsers
        working_directory: ~/project
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: npm install --save-dev firebase-tools
            - run:
                name: Deploy Master to Firebase
                command: npm run firebase-deploy

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
